import { setCredentials } from "@/features/auth/authSlice";
import type { RootState } from "@/store/store";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useDispatch, useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const auth = useSelector((state: RootState) => state.auth);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{auth.id}</p>
        <p>{auth.token}</p>
        <p>{auth.username}</p>
      </main>
    </>
  );
}
